INSERT INTO STUDENT_MASTER VALUES(101,28,'Ashok');
INSERT INTO STUDENT_MASTER VALUES(102,30,'Ramesh');
INSERT INTO STUDENT_MASTER VALUES(103,32,'Sunil');
INSERT INTO STUDENT_MASTER VALUES(104,42,'Basant');